# Generated by Django 3.1.4 on 2021-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='shift',
            field=models.CharField(choices=[('s1', 'Shift_1'), ('s2', 'Shift_2'), ('s3', 'Shift_3')], default='s1', max_length=10, unique_for_date=True),
        ),
    ]
