# Generated by Django 3.1.4 on 2021-02-10 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20210210_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
