# Generated by Django 3.1.4 on 2021-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20210210_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='shift',
            field=models.CharField(choices=[('1', 'Shift_1'), ('2', 'Shift_2'), ('3', 'Shift_3')], max_length=10, unique_for_date='created'),
        ),
    ]
