# Generated by Django 3.1.4 on 2021-02-12 12:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20210211_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[(1, 'Electrical'), (2, 'IT'), (3, 'Bookkeeping'), (4, 'Production')], max_length=20)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('notice', ckeditor.fields.RichTextField(max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='raport',
            options={'ordering': ('created', '-shift')},
        ),
        migrations.AlterField(
            model_name='raport',
            name='team',
            field=models.CharField(choices=[('1', 'Team_1'), ('2', 'Team_2'), ('3', 'Team_3'), ('4', 'Team_4')], default='1', max_length=10),
        ),
    ]
