# Generated by Django 3.1.4 on 2021-02-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20210212_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday_request',
            name='department',
            field=models.PositiveIntegerField(choices=[(1, 'Electrical'), (2, 'IT'), (3, 'Bookkeeping'), (4, 'Production')], max_length=20),
        ),
    ]
