# Generated by Django 3.1.4 on 2021-02-12 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20210212_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday_request',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 2, 12)),
        ),
    ]
