# Generated by Django 3.1.4 on 2021-02-12 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20210212_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday_request',
            name='date_begin',
            field=models.DateField(default=datetime.date(2021, 2, 12)),
        ),
        migrations.AlterField(
            model_name='holiday_request',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 2, 12)),
        ),
    ]
