# Generated by Django 3.1.4 on 2021-02-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_auto_20210217_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raport',
            new_name='Report',
        ),
    ]
