# Generated by Django 3.1.4 on 2021-02-17 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_auto_20210217_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
