# Generated by Django 3.1.4 on 2021-02-17 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_auto_20210217_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
