# Generated by Django 3.1.4 on 2021-02-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
